openapi: 3.0.1
info:
  title: EndpointAPI
  description: API Definition of EndpointAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/endpointapi
- url: https://localhost:8253/endpointapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
